### ISSUE TITLE
Size Mismatch in StyleAvatar training

### ISSUE THREAD

**Issue by mdv3101** [LizhenWangT/StyleAvatar#13]
I am trying to train styleavatar on the newly released code. I used: `python train.py --batch 3 pretrain_dataset/0/`
However I am getting the following error:
```
load dataset: 0 
  0%|                                                                                                         | 0/800000 [00:00<?, ?it/s]
/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/functional.py:3737: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
  0%|                                                                                                         | 0/800000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 387, in <module>
    train(args, loader, back_generator, face_generator, image_generator, discriminator, g_ema, b_g_optim, f_g_optim, i_g_optim, d_optim, device)
  File "train.py", line 189, in train
    l1_loss = torch.mean(torch.abs(fake_img - image)) * 5
RuntimeError: The size of tensor a (1024) must match the size of tensor b (784) at non-singleton dimension 3
```
How to fix this?

**Comment by LizhenWangT** [comment]
Input should be 1536 for full styleavatar, please update the prerprocessing code and read the README.md file carefully.
