### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading file data/104: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by fairynn** [LizhenWangT/StyleAvatar#23]
when testing the python version Full StyleAvatar pretrained model, I got error as below:
python test.py --render_dir test/render --uv_dir test/uv --ckpt pretrained/lizhen_full_python.pt --save_dir output/test
load model: pretrained/lizhen_full_python.pt
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    ckpt = torch.load(args.ckpt)
  File "/root/miniconda3/envs/styleavatar/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/styleavatar/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/styleavatar/lib/python3.8/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/root/miniconda3/envs/styleavatar/lib/python3.8/site-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: PytorchStreamReader failed reading file data/104: invalid header or archive is corrupted

it seems the model file is corrupted

**Comment by LizhenWangT** [comment]
Please check if your pt file is fully downloaded, at least two other users besides me have successfully tested this file.

**Comment by LizhenWangT** [comment]
I have tested it again on Pytoch 1.12. It also works.

**Comment by fairynn** [comment]
Thanks for your reply. I will try it again.
