### ISSUE TITLE
No module named 'fused'

### ISSUE THREAD

**Issue by pv07111998** [LizhenWangT/StyleAvatar#49]
I have prepared the dataset for training and testing the styleavatar model using Python code (FaceVerse). Now when i am trying to train the styleavatar model with "model 0"  executing "python train.py --batch 3 --ckpt pretrained/xxxx.pt path-to-dataset/' is giving the error shown below. how can i resolve it?

ERROR:
PS C:\Users\acer\Downloads\StyleAvatar-main\StyleAvatar-main\styleavatar> python train.py --batch 3 --ckpt "C:\Users\acer\Downloads\StyleAvatar-main\StyleAvatar-main\styleavatar\pretrained\lizhen_full_python.pt" "C:\Users\acer\Desktop\training1"
Traceback (most recent call last):
  File "C:\Users\acer\Downloads\StyleAvatar-main\StyleAvatar-main\styleavatar\train.py", line 13, in <module>
    from networks.generator import DoubleStyleUnet, FeatureGenerator
  File "C:\Users\acer\Downloads\StyleAvatar-main\StyleAvatar-main\styleavatar\networks\generator.py", line 9, in <module>
    from networks.modules import *
  File "C:\Users\acer\Downloads\StyleAvatar-main\StyleAvatar-main\styleavatar\networks\modules.py", line 7, in <module>
    from networks.stylegan2_ops import upfirdn2d
  File "C:\Users\acer\Downloads\StyleAvatar-main\StyleAvatar-main\styleavatar\networks\stylegan2_ops\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\acer\Downloads\StyleAvatar-main\StyleAvatar-main\styleavatar\networks\stylegan2_ops\fused_act.py", line 20, in <module>
    import fused
ModuleNotFoundError: No module named 'fused'

**Comment by justin4ai** [comment]
Facing the same error. Do you have any update about this issue?
