### ISSUE TITLE
Is there any example dataset for testing?

### ISSUE THREAD

**Issue by YiChenCityU** [LizhenWangT/StyleAvatar#5]

**Comment by LizhenWangT** [comment]
We will provide a video for training later. You can also refer to NeRFace: https://github.com/gafniguy/4D-Facial-Avatars or IMAvatar: https://github.com/zhengyuf/IMavatar for training videos.

**Comment by YiChenCityU** [comment]
I used the pretrained model like this: 
python test.py --input_dir input/tdmm --ckpt pretrained/tdmm_lizhen.pt --save_dir output/tdmm --mode 3
load model: pretrained/tdmm_lizhen.pt
But got the error:
Traceback (most recent call last):
  File "/media/eason/edge/NeRF/StyleAvatar/styleunet/test.py", line 118, in <module>
    g_ema.load_state_dict(ckpt["g_ema"], strict=True)
KeyError: 'g_ema

Do you have any idea? Thanks very much.

**Comment by LizhenWangT** [comment]
Sorry, it's a bug. Now you can sovle it by download `tdmm_lizhen.pt` again or just change this line to `g_ema.load_state_dict(ckpt, strict=True)`

**Comment by YiChenCityU** [comment]
Sorry to bother you. I solved the test.py error. But  got a new error when training based on your pretrained model. I just replaced the model according to last reply.

`python train.py --batch 3 --ckpt pretrained/tdmm_lizhen.pt --mode 3 /media/eason/edge/FaceVerse/faceversev3_jittor/output/lizhen/`

load model: pretrained/tdmm_lizhen.pt
Traceback (most recent call last):
  File "/media/eason/edge/NeRF/StyleAvatar/styleunet/train.py", line 328, in <module>
    generator.load_state_dict(ckpt["g"], strict=False)
KeyError: 'g'

**Comment by LizhenWangT** [comment]
It's just a model for testing and can not be used for pretraining. I have uploaded a new file in README.md. Please download the lizhen full model.
